name: Build sbm-utils
on:
  push:
    branches:
      - "**"
    paths:
      - "rework/sbm-utils/**"
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sbm-utils
    steps:
      - name: build-sbm-utils
        uses: actions/checkout@v3
      - name: setup-java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
          cache: maven
      - name: build-project
        run: mvn clean install
